import type { Trip, CityResult, ActivityIdea } from './types';

export const seedCities: CityResult[] = [
  {
    id: 'c-paris',
    name: 'Paris',
    country: 'France',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    tagline: 'The City of Light, art, and world-class gastronomy',
    vibe: ['Romantic', 'Culinary', 'Historic', 'Artistic'],
    avgDailyBudget: 180,
  },
  {
    id: 'c-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800',
    tagline: 'Futuristic innovation blended with ancient tradition',
    vibe: ['Modern', 'Foodie', 'Nightlife', 'Culture'],
    avgDailyBudget: 160,
  },
  {
    id: 'c-nyc',
    name: 'New York',
    country: 'United States',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    tagline: 'The vibrant metropolis that never sleeps',
    vibe: ['Iconic', 'Culture', 'Shopping', 'Fast-Paced'],
    avgDailyBudget: 220,
  },
  {
    id: 'c-rome',
    name: 'Rome',
    country: 'Italy',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    tagline: 'An open-air museum of ancient history and dolce vita',
    vibe: ['Ancient', 'Pasta & Wine', 'Architecture'],
    avgDailyBudget: 140,
  },
  {
    id: 'c-barcelona',
    name: 'Barcelona',
    country: 'Spain',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
    tagline: 'Sun-drenched Mediterranean charm and Gaudi architecture',
    vibe: ['Beach', 'Tapas', 'Design', 'Festive'],
    avgDailyBudget: 130,
  },
  {
    id: 'c-kyoto',
    name: 'Kyoto',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    tagline: 'Serene bamboo groves, golden temples, and geisha traditions',
    vibe: ['Peaceful', 'Temples', 'Nature', 'Tea Ceremony'],
    avgDailyBudget: 140,
  },
];

export const seedActivities: ActivityIdea[] = [
  {
    id: 'a-eiffel',
    title: 'Eiffel Tower Sunset Summit Tour',
    category: 'Sightseeing',
    city: 'Paris',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600',
    description: 'Ascend to the top deck of the Eiffel Tower for golden hour views across Paris.',
    durationHours: 2.5,
    cost: 45,
    rating: 4.9,
  },
  {
    id: 'a-louvre',
    title: 'Louvre Museum Masterpiece Highlights',
    category: 'Culture',
    city: 'Paris',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600',
    description: 'Guided tour showcasing the Mona Lisa, Venus de Milo, and French Crown Jewels.',
    durationHours: 3.0,
    cost: 35,
    rating: 4.8,
  },
  {
    id: 'a-shibuya',
    title: 'Shibuya Crossing & Izakaya Crawl',
    category: 'Food & Drink',
    city: 'Tokyo',
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600',
    description: 'Experience Tokyo nightlife with local yakitori, craft beer, and secret alleys.',
    durationHours: 3.0,
    cost: 50,
    rating: 4.9,
  },
  {
    id: 'a-colosseum',
    title: 'Colosseum & Roman Forum Gladiator Arena',
    category: 'Sightseeing',
    city: 'Rome',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600',
    description: 'Step onto the arena floor where gladiators fought in the heart of ancient Rome.',
    durationHours: 3.0,
    cost: 40,
    rating: 4.9,
  },
  {
    id: 'a-sagrada',
    title: 'Sagrada Familia Architectural Wonder',
    category: 'Culture',
    city: 'Barcelona',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600',
    description: "Explore Antoni Gaudi's towering basilica with stained-glass rainbow light.",
    durationHours: 2.0,
    cost: 35,
    rating: 5.0,
  },
];

export const seedTrips: Trip[] = [
  {
    id: 'trip-1',
    title: 'Grand European Escapade',
    destination: 'Paris, Rome & Barcelona',
    country: 'France / Italy / Spain',
    startDate: '2026-09-10',
    endDate: '2026-09-20',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1000',
    budget: 2800,
    style: 'balanced',
    isPublic: true,
    collaborators: ['Alex', 'Emma'],
    days: [
      {
        id: 'day-1',
        dayNumber: 1,
        date: '2026-09-10',
        activities: [
          {
            id: 'act-1',
            time: '09:30 AM',
            title: 'Louvre Museum Tour',
            category: 'Culture',
            location: 'Rue de Rivoli, Paris',
            cost: 35,
            completed: true,
            notes: 'Mona Lisa & Egyptian antiquities',
          },
          {
            id: 'act-2',
            time: '02:00 PM',
            title: 'Seine River Lunch Cruise',
            category: 'Food & Drink',
            location: 'Pont Neuf, Paris',
            cost: 65,
            completed: false,
          },
          {
            id: 'act-3',
            time: '06:30 PM',
            title: 'Eiffel Tower Sunset Summit',
            category: 'Sightseeing',
            location: 'Champ de Mars, Paris',
            cost: 45,
            completed: false,
          },
        ],
      },
      {
        id: 'day-2',
        dayNumber: 2,
        date: '2026-09-11',
        activities: [
          {
            id: 'act-4',
            time: '10:00 AM',
            title: 'Montmartre & Sacre-Coeur Walk',
            category: 'Sightseeing',
            location: 'Montmartre, Paris',
            cost: 20,
            completed: false,
          },
          {
            id: 'act-5',
            time: '07:30 PM',
            title: 'French Wine Tasting & Bistro Dinner',
            category: 'Food & Drink',
            location: 'Le Marais, Paris',
            cost: 80,
            completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'trip-2',
    title: 'Japan Autumn Discovery',
    destination: 'Tokyo & Kyoto',
    country: 'Japan',
    startDate: '2026-10-15',
    endDate: '2026-10-25',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1000',
    budget: 3200,
    style: 'packed',
    isPublic: false,
    collaborators: ['Alex'],
    days: [
      {
        id: 'day-j1',
        dayNumber: 1,
        date: '2026-10-15',
        activities: [
          {
            id: 'act-j1',
            time: '10:00 AM',
            title: 'Senso-ji Temple & Asakusa',
            category: 'Culture',
            location: 'Asakusa, Tokyo',
            cost: 0,
            completed: false,
          },
          {
            id: 'act-j2',
            time: '06:00 PM',
            title: 'Shibuya Crossing & Izakaya Crawl',
            category: 'Food & Drink',
            location: 'Shibuya, Tokyo',
            cost: 50,
            completed: false,
          },
        ],
      },
    ],
  },
];
